### ISSUE TITLE
Implement geographic topology for Geofabric dataset

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/geofabric-dataset#13]
Generate the topological links between DD->RR->CC.
Redeploy to geofabricld.net.
Rebuild cache.

Refer to https://github.com/CSIRO-enviro-informatics/geofabric-dataset/issues/9

**Comment by benjaminleighton** [comment]
See https://github.com/CSIRO-enviro-informatics/mb16cc-linkset/issues/2

**Comment by benjaminleighton** [comment]
Provisional dataset produced from generalized linkset builder at https://github.com/CSIRO-enviro-informatics/geofabric-dataset/tree/fixed_rr_cc_relationships. This only deals with rr to cc relationships at the moment. Needs review and better testing, not sure paths that are hardcoded will work with cgi deployment on ldapi server). @ashleysommer can you advise. A test deployment needs testing to ensure that known holes are filled in.

**Comment by jyucsiro** [comment]
i assume this is done now?

**Comment by benjaminleighton** [comment]
I've tested it for rr>cc but it would be worth someone else testing it. I've not done dd>rr and I'm not sure there is a problem there? If both of those are addressed then this could be closed. There is cleanup work to do in loci-cache-scripts that is related but wouldn't prevent this from being closed.

**Comment by jyucsiro** [comment]
Tested this in the new cache via pyloci pytests and is passing now.
