### ISSUE TITLE
Label is missing for DrainageDivisions in geofabric rdf views

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/geofabric-dataset#17]
Inspecting the RDF view of the DrainageDivision register items via https://geofabricld.net/drainagedivision/9400203?_view=geofabric&_format=text/turtle

It seems like a label for the feature is missing. In the hyfeatures view, the label exists in :division ... see https://geofabricld.net/drainagedivision/9400203?_view=hyfeatures&_format=text/turtle

Meanwhile, RiverRegion has the predicate dct:title mapped from the hyfeatures, see https://geofabricld.net/riverregion/9400220?_view=geofabric&_format=text/turtle

Could we add it in into the geofabric view and thus enable it to be queried via the loci cache?

**Comment by ashleysommer** [comment]
Fixed by https://github.com/CSIRO-enviro-informatics/geofabric-dataset/commit/86c4a4a9121bceb48d47c01fd6222af0e7bfe956

**Comment by jyucsiro** [comment]
Thanks for this. The label is rendering now.
