### ISSUE TITLE
Include defaultGeometry in geofabricld feature instances

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/geofabric-dataset#21]
This issue is to explore adding defaultGeometry in geofabricld feature instances in the same way as the other Loc-I datasets do, e.g. asgsld.net, gnafld.net, to enable consistent content across the LD products.

See example:
https://asgsld.net/2016/object?_format=text%2Fturtle&uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgs2016%2Fmeshblock%2F50055290000&_view=asgs 
 
This would require reprocessing of the geofabric dataset to include the geometry

**Comment by dr-shorthair** [comment]
`geo:defaultGeometry` is mostly for when there is more than one geometry, typically to give a hint to processors which one to use for portrayal on a map. We could interpret it in some other way of course.

**Comment by benjaminleighton** [comment]
https://github.com/CSIRO-enviro-informatics/geofabric-dataset/tree/feature/hasGeometry

**Comment by jyucsiro** [comment]
GIven the new Geometry Data Service hosting Loc-I geometries, defer this issue and possibly deprecate. Review in Feb.
