### ISSUE TITLE
enable cors on appropriate views

### ISSUE THREAD

**Issue by benjaminleighton** [CSIRO-enviro-informatics/geofabric-dataset#24]

**Comment by ashleysommer** [comment]
Fixed by https://github.com/CSIRO-enviro-informatics/geofabric-dataset/commit/98dba83809dafc56944bb01c785e34895b817606

**Comment by jyucsiro** [comment]
thanks - is it deployed?

**Comment by ashleysommer** [comment]
Yes, the currently deployed version has CORS enabled.
