### ISSUE TITLE
Internal Server Error on one specific Drainage Division

### ISSUE THREAD

**Issue by ashleysommer** [CSIRO-enviro-informatics/geofabric-dataset#3]
See this error here:
http://geofabricld.net/drainagedivision/9400215

But all others work, eg:
http://geofabricld.net/drainagedivision/9400214

There are only 13 drainage divisions in the whole country. Why is 9400214 different than the other 12?

**Comment by edmondchuc** [comment]
I stumbled across this by chance but found that this instance is not resolving either.
See: http://geofabricld.net/drainagedivision/9400210

**Comment by ashleysommer** [comment]
Fixed in https://github.com/CSIRO-enviro-informatics/geofabric-dataset/commit/06d5de6c8a7dae6fe6601dd6039e1adfcf1bdcbc
